### ISSUE TITLE
Animated circle has small pixel gap

### ISSUE THREAD

**Issue by mathieuboblet** [dylanfisher/roserage#1]
Getting a little bit of the spinning image sneaking out from the sides of the circle knockout

In Safari:
![image](https://cloud.githubusercontent.com/assets/8378025/20457816/76980dd2-ae61-11e6-8a75-8aa6805d367c.png)

In Firefox:
![image](https://cloud.githubusercontent.com/assets/8378025/20457820/96cfe87c-ae61-11e6-89ef-863442e715dd.png)

In Chrome:
![image](https://cloud.githubusercontent.com/assets/8378025/20457813/5b7de54e-ae61-11e6-8d43-89c79035c38e.png)

**Comment by dylanfisher** [comment]
There is some sub-pixel antialiasing issues that cause this at certain screen sizes - so it's tricky to fix. I did make a change that affects it, so let me know if it's looking better for you. Otherwise I'll have to keep tweaking it.

**Comment by dylanfisher** [comment]
This should be a little more reliable now. I can still get it to break at one particular width, but it's better than it was before. I think good enough, unless it still looks bad on your computer?
